### PR TITLE
HW-2 Issue676

### LINKED ISSUE #676: Bibliography within a bibliography
I was working with LibreOffice writer creating a references section, and writer crashed while Jabref was connected. Now, when I try to add references, Jabref is creating a new bibliography within the existing one and starting over at 1. I can't find any issues with the bibtex file, and Jabref doesn't seem to throw any errors. I'm working on Linux.

### PR DESCRIPTION
**Pull request by ssjayakumar**
Homework 2 - Issue 676 Pull Request

As a team, we discussed and I took logic.casechanger and logic.journals
And I made sure,

-There are no Checkstyle issues.
-There are no SpotBugs issues.
-There are no javadoc errors.
-All tests in the file pass.

Will you get full credit on this assignment?
-I'm hoping to get full credit on thie assignment.

How long did you spend on the assignment?
-I spent around 4-5 hours totally.

What problems did you encounter, and how did you deal with them?
-I had some issues with installing jabref, where i got some errors like mising JAVA_HOME, then I used chatgpt to learn what it was about and what i could do to fix it. then it suggested to set JAVA_HOME as environment variable, which I did, then everything worked out perfectly.
Fixes https://github.com/JabRef/jabref/issues/676

What help did you give or receive on this assignment (including answering these question)? What was your AI usage?
-I used Chatpgt 5 to check if the changes i made (parameterized tests) were correct, and used AI during installing jabref.

### CODE REVIEW

**Comment by espertusnu** [comment]
I can't review this because it includes other changes. We can discuss this at our appointment.

File: jablib/src/test/java/org/jabref/logic/formatter/casechanger/ProtectTermsFormatterTest.java [hunk 1]
```diff
@@ -24,36 +26,40 @@ void setUp() {
                         List.of(), List.of(), List.of())));
     }
 
-    @Test
-    void singleWord() {
-        assertEquals("{VLSI}", formatter.format("VLSI"));
+    @ParameterizedTest(name = "format(\"{1}\") should return \"{0}\"")
```
Comment (espertusnu) [inline jablib/src/test/java/org/jabref/logic/formatter/casechanger/ProtectTermsFormatterTest.java:29]: Could you tell me what this means and why you added it?

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationParserTest.java [hunk 2]
```diff
@@ -25,24 +28,23 @@ void setup(@TempDir Path tempDir) {
...
 
-    @Test
-    void readingFileFromCSVWithComma() throws IOException {
-        String testAbbrev = "Long Name,L.N.,L.N.";
-        try (BufferedWriter writer = Files.newBufferedWriter(csvFile, StandardCharsets.UTF_8)) {
-            writer.write(testAbbrev);
-        }
-        parser.readJournalListFromFile(csvFile);
-        assertEquals(Set.of(abbreviation), parser.getAbbreviations());
+    private static Stream<Arguments> provideDelimiterTestCases() {
```
Comment (espertusnu) [inline jablib/src/test/java/org/jabref/logic/journals/AbbreviationParserTest.java:41]: I think these argument providers usually go right above the test that uses them, but correct me if I'm wrong.

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java [hunk 3]
```diff
@@ -1,120 +1,139 @@
...
-    void abbreviationsWithTrailingSpaces() {
-        Abbreviation abbreviation = new Abbreviation("Long Name", "L. N.");
-
-        assertEquals("Long Name", abbreviation.getName());
-        assertEquals("L. N.", abbreviation.getAbbreviation());
-        assertEquals("L N", abbreviation.getDotlessAbbreviation());
-        assertEquals("L. N.", abbreviation.getShortestUniqueAbbreviation());
+    @ParameterizedTest(name = "{0}")
+    @MethodSource("provideAbbreviationTestCases")
+    void testAbbreviationProperties(String testName, Abbreviation abbreviation,
```
Comment (espertusnu) [inline jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java:16]: Try starting a new line after the left parenthesis.

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java [hunk 4]
```diff
@@ -1,120 +1,139 @@
...
-        assertEquals("L. N.", abbreviation.getNext("Long Name"));
-        assertEquals("L N", abbreviation.getNext("L. N."));
-        assertEquals("Long Name", abbreviation.getNext("L N"));
+    private static Stream<Arguments> provideGetNextTestCases() {
+        Abbreviation abbrev1 = new Abbreviation("Long Name", "L. N.");
+        Abbreviation abbrev2 = new Abbreviation("Long Name", "L. N.", "LN");
+
+        return Stream.of(
+                // getNextElement tests
+                Arguments.of("getNextElement - Long Name to L. N.", abbrev1, "Long Name", "L. N."),
```
Comment (espertusnu) [inline jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java:83]: I don't know where these strings came from.

**Comment by espertusnu** [comment]
Could you please come in person to my Wednesday office hours this week?

**Review by espertusnu — CHANGES_REQUESTED** [review]
It looks like some of my previous comments might not have gone through. Sorry about that!

File: jablib/src/test/java/org/jabref/logic/formatter/casechanger/ProtectTermsFormatterTest.java (hunk 1 above)
Comment (ssjayakumar) [reply jablib/src/test/java/org/jabref/logic/formatter/casechanger/ProtectTermsFormatterTest.java:29]: Screenshot 2025-10-26 185100

I'm not sure, I'm unable to see that in my code. I believe I didn't add that line.

Comment (espertusnu) [reply jablib/src/test/java/org/jabref/logic/formatter/casechanger/ProtectTermsFormatterTest.java:29]: It's not in the current version in your code. It was in this commit:
https://github.com/sandeepsamueljayakumar/jabref/pull/1/commits/b7913bfc939f748f81367430d44101af11aff1df

Please let me know what it means and why you added it.

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationParserTest.java (hunk 2 above)
Comment (espertusnu) [reply jablib/src/test/java/org/jabref/logic/journals/AbbreviationParserTest.java:41]: Please respond to this comment.

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java (hunk 4 above)
Comment (espertusnu) [reply jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java:83]: Please tell me where these strings came from. I don't see them in the original file.

**Review by espertusnu — CHANGES_REQUESTED** [review]
@sandeepsamueljayakumar I re-reviewed your code as you requested, but you still had not responded to all my comments. Please view the PR conversation on github and scroll down the page to see comments that have not been responded to. I will wait until you have responded to all outstanding comments before doing further review of your code. 

Please ask if you don't understand how to view comments. That is also something that Hazel could help you with.

File: jablib/src/test/java/org/jabref/logic/formatter/casechanger/ProtectTermsFormatterTest.java (hunk 1 above)
Comment (ssjayakumar) [reply jablib/src/test/java/org/jabref/logic/formatter/casechanger/ProtectTermsFormatterTest.java:29]: This line makes the method a JUnit 5 parameterized test, so it runs once for each case from provideTestCases.
The name = "format(\"{1}\") should return \"{0}\"" part is just the display text: {1} = input, {0} = expected (the backslashes escape the quotes).
I added it to avoid copy-pasting similar tests and to make failures easier to read (e.g., it shows format("VLSI") should return "{VLSI}").

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationParserTest.java (hunk 2 above)
Comment (ssjayakumar) [reply jablib/src/test/java/org/jabref/logic/journals/AbbreviationParserTest.java:41]: Yes you are right, positioning a @MethodSource providers directly above the tests improves readability

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java (hunk 3 above)
Comment (ssjayakumar) [reply jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java:16]: Apologies for the oversight, I’ll reformat the method signature to break after the left parenthesis and wrap the parameters consistently.

File: jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java (hunk 4 above)
Comment (ssjayakumar) [reply jablib/src/test/java/org/jabref/logic/journals/AbbreviationTest.java:83]: Thanks for commenting this. To be fully transparent: I used ChatGPT to scaffold these parameterized tests. The string values ("Long Name", "L. N.", "L N", "LN") reflect the intended Abbreviation state transitions (full → dotted → dotless → shortest) and they also match the behavior that was covered by the earlier single-case test I replaced.

**Review by espertusnu — APPROVED** [review]
